name: citylife
description: An app for your impressions on our lovely city.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  email_validator: ^1.0.6
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter_facebook_auth: ^2.0.2
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_twitter_login: ^1.1.0
  github_sign_in: ^0.0.3
  google_fonts: ^1.1.2
  google_maps_flutter: ^1.1.1
  google_sign_in: ^4.5.9
  gradient_widgets: ^0.5.2
  http: ^0.12.2
  intl: ^0.16.1
  latlong: ^0.6.1
  location: ^3.2.4
  provider: ^4.3.3
  shared_preferences: ^2.0.3
  uni_links: ^0.4.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  crypto: null
  mockito: null
  pedantic: null
module:
  androidX: true

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/launcher_icon.png"
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/CityLife_Logo.svg
    - assets/images/Google_Logo.png
    - assets/images/Twitter_Logo.png
    - assets/images/GitHub_Logo.png
    - assets/images/Facebook_Logo.png
    - assets/images/avatar_1.png
    - assets/images/avatar_2.png
    - assets/images/avatar_3.png
    - assets/images/avatar_4.png
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
tags:
  widgets:
  screens:
  utils:
