name: citylife
description: An app for your impressions on our lovely city.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  email_validator: ^1.0.6
  firebase_analytics: ^7.0.1
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  firebase_storage: ^8.0.3
  firebase_storage_web: ^1.0.3
  flutter_plugin_android_lifecycle: ^2.0.1
  flutter_facebook_auth: ^3.3.2+2
  flutter_facebook_auth_platform_interface: ^2.4.1
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_twitter_login: 
    git: git://github.com/eudangeld/flutter_twitter_login.git
  geocoder: ^0.2.1
  github_sign_in: ^0.0.3
  google_maps_flutter:
  google_sign_in: ^4.5.9
  gradient_widgets: ^0.5.2
  http: ^0.13.0
  image_picker: ^0.7.4
  intl: ^0.17.0
  latlong: ^0.6.1
  location: ^4.1.1
  path: 
  provider: ^4.3.3
  plugin_platform_interface: ^2.0.0
  shared_preferences: ^2.0.3
  flutter_spinkit: "^4.1.2"
  steps_indicator: ^1.2.0
  uni_links: ^0.4.0
  url_launcher: ^6.0.3
  geocoding: 
  open_mail_app:
  qr_flutter: 
  pin_code_fields:
  flutter_animated_dialog: 
  confetti:
  fluster:

dev_dependencies:
  flutter_test:
    sdk: flutter
  crypto:
  mockito:
  pedantic:
module:
  androidX: true

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/launcher_icon.png"
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/CityLife_Logo.svg
    - assets/images/Google_Logo.png
    - assets/images/Twitter_Logo.png
    - assets/images/GitHub_Logo.png
    - assets/images/Facebook_Logo.png
    - assets/images/avatar_1.jpg
    - assets/images/avatar_2.jpg
    - assets/images/avatar_3.jpg
    - assets/images/avatar_4.jpg
    - assets/images/avatar_5.jpg
    - assets/images/avatar_6.jpg
    - assets/images/avatar_7.jpg
    - assets/images/avatar_8.jpg
    - assets/images/avatar_9.jpg
    - assets/images/avatar_10.jpg
    - assets/images/avatar_11.jpg
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
tags:
  widgets:
  screens:
  utils:
