name: deploy 

on:
  push:
    branches: 
      - master
  pull_request:
      branches: 
        - master

defaults:
  run:
    working-directory: ./citylife

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
      - name: Setting up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.1'
          channel: 'beta'
      - name: Fetching dependencies
        run: flutter pub get
      - name: Running application tests
        run: flutter test --coverage && curl -s https://codecov.io/bash -o codecov.sh
      - name: Upload Test coverage to CodeCov project
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f ./coverage/lcov.info
        shell: bash
        
#       - name: Upload Test coverage to CodeCov project
#         uses: codecov/codecov-action@v1.2.1 
#         with: 
#           token: ${{ secrets.CODECOV_TOKEN }} 
#           file: ./coverage/lcov.info
#           fail_ci_if_error: false
#           working-directory: ./citylife
#           verbose: true     
