name: Flutter 

on:
  push:
    branches: 
      - master
  pull_request:
      branches: 
        - master

defaults:
  run:
    working-directory: ./citylife

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
      - name: Setting up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.1'
          channel: 'beta'
      - name: Fetching dependencies
        run: flutter pub get
      - name: Running application tests
        run: flutter test --coverage && curl -s https://codecov.io/bash -o codecov.sh
      - name: Upload Test coverage to CodeCov project
        uses: codecov/codecov-action@v1.2.1 
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: coverage/lcov.info
          fail_ci_if_error: true
          working-directory: ./citylife
          verbose: true
      - name: Build Flutter apk
        run: flutter build apk --dart-define=CITYLIFE_TWITTER_CONSUMER_KEY=${{ secrets.CITYLIFE_TWITTER_CONSUMER_KEY }} --dart-define=CITYLIFE_TWITTER_CONSUMER_SECRET=${{ secrets.CITYLIFE_TWITTER_CONSUMER_SECRET }} --dart-define=CITYLIFE_GITHUB_CLIENT_ID=${{ secrets.CITYLIFE_GITHUB_CLIENT_ID }} --dart-define=CITYLIFE_GITHUB_CLIENT_SECRET=${{ secrets.CITYLIFE_GITHUB_CLIENT_SECRET }} --dart-define=CITYLIFE_AUTH_REDIRECT_URL=${{ secrets.CITYLIFE_AUTH_REDIRECT_URL }} --dart-define=API_ENDPOINT=${{ secrets.API_ENDPOINT }}
      - name: Deploy apk to Firebase App Distribution Service
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: beta-testers
          file: build\app\outputs\flutter-apk\app-release.apk
          debug: true
        
